// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANhsPjhBwA_gtg8wdGIyfSj6-DJmy9fa4',
    appId: '1:7124589496:web:9e7eb8215f1d9c99a0cd4d',
    messagingSenderId: '7124589496',
    projectId: 'chat-app-bbd0f',
    authDomain: 'chat-app-bbd0f.firebaseapp.com',
    storageBucket: 'chat-app-bbd0f.appspot.com',
    measurementId: 'G-Q8SSTGJ2EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI24FVtAcRQ166vUSa_toCCVQrXZx4K4o',
    appId: '1:7124589496:android:4e16db84990d08d6a0cd4d',
    messagingSenderId: '7124589496',
    projectId: 'chat-app-bbd0f',
    storageBucket: 'chat-app-bbd0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3WUFHOOAzZ-fxZdq7lY7j7ME-uyTTx9c',
    appId: '1:7124589496:ios:a449009853db3a26a0cd4d',
    messagingSenderId: '7124589496',
    projectId: 'chat-app-bbd0f',
    storageBucket: 'chat-app-bbd0f.appspot.com',
    iosClientId: '7124589496-uskif6lmktof427pr3q4etfbu2vcntvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3WUFHOOAzZ-fxZdq7lY7j7ME-uyTTx9c',
    appId: '1:7124589496:ios:a449009853db3a26a0cd4d',
    messagingSenderId: '7124589496',
    projectId: 'chat-app-bbd0f',
    storageBucket: 'chat-app-bbd0f.appspot.com',
    iosClientId: '7124589496-uskif6lmktof427pr3q4etfbu2vcntvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
